apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator-my
spec:
  profile: default
  # This is done to merge multiple slashes in http URLs, otherwise, MOSIP APIs may not work
  meshConfig:
    pathNormalization:
      normalization: MERGE_SLASHES
    defaultConfig:
      proxyMetadata:
        ISTIO_META_IDLE_TIMEOUT: 0s
      holdApplicationUntilProxyStarts: true
      gatewayTopology:
        numTrustedProxies: 2
    extensionProviders:
    - name: oauth2-proxy
      envoyExtAuthzHttp:
        service: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port: 80
        headersToDownstreamOnDeny:
        - content-type
        - set-cookie
        headersToUpstreamOnAllow:
        - authorization
        - path
        - x-auth-access-token
        - x-auth-request-user
        - x-auth-request-email
        - x-auth-request-preferred-username
        - x-auth-request-groups
        includeAdditionalHeadersInCheck:
          X-Auth-Request-Redirect: https://%REQ(:authority)%%REQ(:path)%
        includeRequestHeadersInCheck:
        - authorization
        - cookie
  components:
    ingressGateways:
      ## Public access to external ingress gateway is disabled by default. Enable it in production.
      - name: istio-ingressgateway
        enabled: false
        k8s:
          env:
          - name: ISTIO_META_IDLE_TIMEOUT
            value: 300s
          serviceAnnotations:
            oci.oraclecloud.com/load-balancer-type: "lb"
            service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
            service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"    
            service.beta.kubernetes.io/oci-load-balancer-tls-secret: mosip-sandbox-cert-secret
      - name: istio-ingressgateway-internal
        enabled: true
        label:
            istio: ingressgateway-internal
        k8s:
          env:
          - name: ISTIO_META_IDLE_TIMEOUT
            value: 300s
          serviceAnnotations:
            oci.oraclecloud.com/load-balancer-type: "lb"
            #service.beta.kubernetes.io/oci-load-balancer-internal: "true"
            service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
            service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/oci-load-balancer-tls-secret: mosip-sandbox-cert-secret
            #service.beta.kubernetes.io/oci-load-balancer-subnet1: ""
            #oci.oraclecloud.com/oci-network-security-groups: ""
            #oci.oraclecloud.com/security-rule-management-mode: "None"            
          service:
            ports:
            - port: 15021
              targetPort: 15021
              name: status-port
              protocol: TCP
            - port: 80
              targetPort: 8080
              name: http2
              protocol: TCP
            - port: 443
              targetPort: 8080
              name: https
              protocol: TCP
            # additional ports
            - port: 61616
              targetPort: 61616
              name: activemq
              protocol: TCP
            - port: 5432
              targetPort: 5432
              name: postgres
              protocol: TCP
