hostname: rancher.mosip.net

ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  extraAnnotations:
      kubernetes.io/ingress.class: nginx
  tls: 
    source: rancher
    
rancherImage: rancher/rancher

replicas: 2

bootstrapPassword: 'admin'
